use_frameworks!

platform :ios, '9.0'

target 'YFTagView_Example' do
  pod 'YFTagView', :path => '../'
  pod 'Masonry'
  pod 'YFPositionButton'

  target 'YFTagView_Tests' do
    inherit! :search_paths
  end
end
